### ISSUE TITLE
Kreiranje baze

### ISSUE THREAD

**Issue by KorosecN13** [VidicL13/Trip_wallet#1]
Zanima naju, kako lahko uporabnik dostopa do baze drugega uporabnika v PostgreSQL, dodala sva že vsa dovoljenja, tudi @MarvinHerzog in @jaanos (Grant all).

Baza je zgrajena pod imenom 'lukav', ime baze: 'sem2018_lukav'

**Comment by jaanos** [comment]
Sem zdaj v phppgadmin vklopil, da lahko vsak vidi vse baze, na katere se lahko poveže. Povezava s programskim vmesnikom je sicer že prej delovala.

**Comment by VidicL13** [comment]
hvala
