### ISSUE TITLE
Težava pri nalaganju plugin-a

### ISSUE THREAD

**Issue by VidicL13** [VidicL13/Trip_wallet#4]
Pri nalaganju datoteke, ki jo najdete pod Trip_wallet/Trip_wallet/webapp/templates/webapp/untitled.html imam težavo, saj se selectbox ne naloži v željeni obliki. Nalo ži se v osnovni obliki le stil se mu spremeni.

uporabljal sem plugin [chosen](https://harvesthq.github.io/chosen/)

imate morda kakšno idejo, kje tiči napaka?

**Comment by MarvinHerzog** [comment]
V `head.html`, znotraj `body` je potrebno spremeniti vrstni red scriptov. Prav tako je potrebno premakniti vrstici "block" pod te skripte. Meni dela takšen vrstni red:

```
<body>
    <script src="{% static 'webapp/bootstrap/js/bootstrap.min.js' %}"></script> 
    <script src="{% static 'webapp/js/jquery-3.3.1.min.js' %}"></script>	
    <script src="{% static 'webapp/js/script.min.js' %}"></script>
    <script src="{% static 'webapp/js/chosen.jquery.min.js' %}"></script>

    {% block content %}
    {% endblock %}
</body>
```
